[package]
name = "deploya"
version = "0.1.0"
edition = "2024"

[dependencies]
bollard = { path="../bollard" }
futures-util = "0.3.31"
tokio = { version = "1.44.2", features = ["rt", "rt-multi-thread", "macros"] }
