[package]
name = "deploya"
version = "0.1.0"
edition = "2024"
license = "MIT"
description = "simple continuous CD container upgrades"
repository = "https://github.com/HerrMuellerluedenscheid/deploya"
authors = ["marius.kriegerowski@gmail.com"]

[dependencies]
bollard = { git = "https://github.com/HerrMuellerluedenscheid/bollard.git" }
futures-util = "0.3.31"
tokio = { version = "1.44.2", features = ["rt", "rt-multi-thread", "macros"] }
log = "0.4.27"
env_logger = "0.11.8"
serde_json = "1.0.140"
thiserror = "2.0.12"
sled = "0.34.7"
clap = "4.5.37"
