services:
  hoister:
    build: .
    image: emrius11/hoister:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    security_opt:
      - no-new-privileges:true
    cap_add:
      - SETGID
    depends_on:
      - example

  example:
    build:
      context: .
      dockerfile: works.Dockerfile
    labels:
      - "hoister.enable=true"
    image: emrius11/example:latest
