name: Deploy

on:
  workflow_dispatch:
  push:
    tags:
      - '*.*.*'

permissions:
  contents: write

env:
  CARGO_TERM_COLOR: always

jobs:

  release-linux:
    timeout-minutes: 15
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: install cargo-deb
        run: cargo install cargo-deb
      - name: Build
        run: cargo build --release
      - name: Build Debian
        run: cargo deb
      - name: Rename artifact
        run: cp target/debian/deploya_*.deb target/debian/deploya-${{ github.ref_name }}.deb
      - name: Upload .deb package
        uses: actions/upload-artifact@v4
        with:
          name: deploya-${{ github.ref_name }}.deb
          path: target/debian/deploya-${{ github.ref_name }}.deb
      - name: Upload binary
        uses: actions/upload-artifact@v4
        with:
          name: deploya-binary-${{ github.ref_name }}
          path: target/release/deploya
      - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            target/debian/deploya-*.deb
            target/release/deploya

  release-windows:
    runs-on: windows-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v2
      - name: Build Release
        run: cargo build --release
      - name: upload artefact
        uses: actions/upload-artifact@v4
        with:
          name: deploya.exe
          path: target/release/deploya.exe

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: target/release/deploya.exe

  release-osx:
    runs-on: macos-latest
    timeout-minutes: 15
    steps:
    - uses: actions/checkout@v2
    - name: Build Release
      run: cargo build --release
    - name: Rename artifact
      run: cp target/release/deploya target/release/deploya-osx

    - name: upload artefact
      uses: actions/upload-artifact@v4
      with:
        name: deploya-osx
        path: target/release/deploya-osx

    - name: Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: target/release/deploya-osx
