name: Deploy

on:
  workflow_dispatch:
  push:
    tags:
      - '*.*.*'

permissions:
  contents: write

env:
  CARGO_TERM_COLOR: always

jobs:

  release-linux-arm64:
    timeout-minutes: 15
    runs-on: ubuntu-24.04-arm
    steps:
      - uses: actions/checkout@v4

      - name: Install cargo-deb
        run: cargo install cargo-deb

      - name: Build
        run: cargo build --release

      - name: Build Debian package
        run: cargo deb

      - name: Rename artifacts
        run: |
          cp target/debian/hoister_*.deb target/debian/hoister-arm64-${{ github.ref_name }}.deb
          cp target/release/hoister target/release/hoister-binary-arm64-${{ github.ref_name }}

      - name: Upload .deb package
        uses: actions/upload-artifact@v4
        with:
          name: hoister-arm64-${{ github.ref_name }}.deb
          path: target/debian/hoister-arm64-${{ github.ref_name }}.deb

      - name: Upload binary
        uses: actions/upload-artifact@v4
        with:
          name: hoister-binary-arm64-${{ github.ref_name }}
          path: target/release/hoister-binary-arm64-${{ github.ref_name }}

      - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            target/debian/hoister-arm64-${{ github.ref_name }}.deb
            target/release/hoister-binary-arm64-${{ github.ref_name }}

  release-linux:
    timeout-minutes: 15
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: install cargo-deb
        run: cargo install cargo-deb
      - name: Build
        run: cargo build --release
      - name: Build Debian
        run: cargo deb
      - name: Rename artifact
        run: cp target/debian/hoister_*.deb target/debian/hoister-${{ github.ref_name }}.deb
      - name: Upload .deb package
        uses: actions/upload-artifact@v4
        with:
          name: hoister-${{ github.ref_name }}.deb
          path: target/debian/hoister-${{ github.ref_name }}.deb
      - name: Upload binary
        uses: actions/upload-artifact@v4
        with:
          name: hoister-binary-${{ github.ref_name }}
          path: target/release/hoister
      - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            target/debian/hoister-*.deb
            target/release/hoister

  release-windows:
    runs-on: windows-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v4
      - name: Build Release
        run: cargo build --release
      - name: upload artefact
        uses: actions/upload-artifact@v4
        with:
          name: hoister.exe
          path: target/release/hoister.exe

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: target/release/hoister.exe

  release-osx:
    runs-on: macos-latest
    timeout-minutes: 15
    steps:
    - uses: actions/checkout@v4
    - name: Build Release
      run: cargo build --release
    - name: Rename artifact
      run: cp target/release/hoister target/release/hoister-osx

    - name: upload artefact
      uses: actions/upload-artifact@v4
      with:
        name: hoister-osx
        path: target/release/hoister-osx

    - name: Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: target/release/hoister-osx
